spring:

  application:
    name: oar-rmm-service
  
  data:
    mongodb:
      host: localhost
      port: 27017
      database: TestDB
      user:
      password:
      
  profiles:
    active:
      dev
      
dbcollections: 
         taxonomy: taxonomy
         resources: apis
         records: record 
         recordfields: fields
      
server: 
    port: 8085
    contextPath: /rmm
    error:
      include-stacktrace: never
    connection-timeout: 60000
    max-http-header-size: 8192
    tomcat:
      accesslog:
        directory: logs
        enabled: false
    
logging:
  file: rmmapp.log
  path : /var/log/rmm-api/
  exception-conversion-word: '%wEx'
  
security:
    headers:
      frame: true
      xss: true
      hsts: all
    enable-csrf: false
